import {
  Subject,
  Note,
  KanbanTask,
  FlashcardDeck,
  CalendarEvent,
  ResourceItem,
  UserStats,
  Badge,
  SystemSettings,
} from "@/types";

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: "sub-cs",
    name: "Computer Science",
    category: "Software Engineering",
    mastery: 94,
    color: "emerald",
    examDate: "2026-07-15",
    notesCount: 22,
    pendingCount: 1,
  },
  {
    id: "sub-math",
    name: "Advanced Mathematics",
    category: "Calculus & Linear Algebra",
    mastery: 82,
    color: "indigo",
    examDate: "2026-07-25",
    notesCount: 14,
    pendingCount: 2,
  },
  {
    id: "sub-chem",
    name: "Organic Chemistry",
    category: "Molecular Biology",
    mastery: 45,
    color: "rose",
    examDate: "2026-08-02",
    notesCount: 8,
    pendingCount: 3,
  },
  {
    id: "sub-hist",
    name: "World History",
    category: "History of Art",
    mastery: 60,
    color: "amber",
    examDate: "2026-07-30",
    notesCount: 19,
    pendingCount: 1,
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: "note-1",
    title: "Data Structures & Algorithms Overview",
    subjectId: "sub-cs",
    folder: "Computer Science",
    content: `## Data Structures Overview\n\nData structures are essential blocks for organizing and storing data efficiently.\n\n### Key Structures\n1. **Binary Search Tree (BST)**:\n   - Average Search: O(log n)\n   - Worst Search: O(n) (unbalanced)\n2. **Red-Black Tree**:\n   - Self-balancing BST\n   - Height is guaranteed to be O(log n)\n\n### Graph Traversal Algorithms\n- **Breadth-First Search (BFS)**: Uses a queue. Finds shortest path in unweighted graphs.\n- **Depth-First Search (DFS)**: Uses a stack (or recursion). Ideal for exploring all paths and cycle detection.`,
    pinned: true,
    tags: ["EXAM", "PRIORITY"],
    lastModified: "2026-07-10 14:32",
  },
  {
    id: "note-2",
    title: "The Renaissance & Modernity Art Forms",
    subjectId: "sub-hist",
    folder: "History of Art",
    content: `## The Renaissance\n\nThe Renaissance was a fervent period of European cultural, artistic, political and scientific "rebirth" following the Middle Ages.\n\n### Core Artistic Techniques\n- **Linear Perspective**: Pioneered by Filippo Brunelleschi.\n- **Chiaroscuro**: The use of strong contrasts between light and dark.\n- **Sfumato**: Fine shading that produces soft transitions between colors.\n\n### Influential Masters\n1. **Michelangelo**: Known for the Sistine Chapel ceiling and the David.\n2. **Leonardo da Vinci**: The archetypal "Renaissance Man."\n3. **Raphael**: Master of grace and harmony.`,
    pinned: true,
    tags: ["EXAM"],
    lastModified: "2026-07-09 11:20",
  },
  {
    id: "note-3",
    title: "Calculus II Integration Techniques",
    subjectId: "sub-math",
    folder: "Advanced Calculus",
    content: `## Advanced Integration Techniques\n\nMastery of integration is core to Advanced Calculus.\n\n### 1. Integration by Parts\nBased on the product rule for differentiation.\n\n### 2. Trigonometric Substitution\nUsed when integrands contain square roots of quadratic forms.`,
    pinned: true,
    tags: ["PRIORITY"],
    lastModified: "2026-07-08 17:05",
  },
  {
    id: "note-4",
    title: "Introduction to Organic Synthesis & Alkanes",
    subjectId: "sub-chem",
    folder: "Organic Chemistry",
    content: `## Alkanes and Organic Basics\n\nAlkanes are saturated hydrocarbons containing only single bonds.\n\n### Chemical Properties\n- **Formula**: CnH(2n+2)\n- **Hybridization**: sp3 hybridized carbons with 109.5 degree bond angles.\n- **Reactivity**: Generally inert, but undergo free-radical halogenation and combustion.`,
    pinned: false,
    tags: ["DRAFT"],
    lastModified: "2026-07-05 09:12",
  },
];

export const INITIAL_TASKS: KanbanTask[] = [
  {
    id: "task-1",
    title: "Database Normalization Report",
    subjectId: "sub-cs",
    description: "Write normal forms up to BCNF with concrete database schema examples and submit PDF.",
    status: "todo",
    dueDate: "2026-07-14",
    priority: "high",
  },
  {
    id: "task-2",
    title: "Micro-Market Equilibrium Essay",
    subjectId: "sub-math",
    description: "Draft the graphical analysis, mathematical equilibrium proof and state policy variables.",
    status: "progress",
    dueDate: "2026-07-16",
    priority: "medium",
  },
  {
    id: "task-3",
    title: "Cognitive Bias Lab Report Draft",
    subjectId: "sub-chem",
    description: "Check statistics section, run ANOVA tests and ensure all tables and graphs are aligned.",
    status: "review",
    dueDate: "2026-07-12",
    priority: "low",
  },
  {
    id: "task-4",
    title: "Linear Algebra Problem Set #4",
    subjectId: "sub-math",
    description: "Completed 10 eigenvector calculations, verified with Python code, and submitted on Portal.",
    status: "completed",
    dueDate: "2026-07-08",
    priority: "high",
  },
];

export const INITIAL_DECKS: FlashcardDeck[] = [
  {
    id: "deck-1",
    name: "Medical Terminology",
    subjectId: "sub-chem",
    description: "Anatomy & Physiology key Latin/Greek stems, prefixes, and suffixes.",
    category: "Medicine",
    progress: 75,
    cards: [
      { id: "c1-1", question: "What is the meaning of the suffix '-itis'?", answer: "Inflammation (e.g., Hepatitis, Carditis)", status: "good" },
      { id: "c1-2", question: "What is the meaning of the stem 'hepat-'?", answer: "Liver (e.g., Hepatocyte, Hepatomegaly)", status: "good" },
      { id: "c1-3", question: "What is the meaning of the stem 'myo-'?", answer: "Muscle (e.g., Myocardium, Myopathy)", status: "easy" },
      { id: "c1-4", question: "What is the meaning of the prefix 'tachy-'?", answer: "Fast or rapid (e.g., Tachycardia)", status: "again" },
    ],
  },
  {
    id: "deck-2",
    name: "Physics Formulas & Laws",
    subjectId: "sub-math",
    description: "Advanced Mechanics, Electromagnetism, and Quantum variables.",
    category: "Physics",
    progress: 42,
    cards: [
      { id: "c2-1", question: "What is Kepler's Third Law?", answer: "The square of the orbital period is proportional to the cube of the semi-major axis (T² ∝ a³).", status: "hard" },
      { id: "c2-2", question: "State Gauss's Law of Electromagnetism.", answer: "The net electric flux through any closed surface equals the net enclosed charge divided by ε₀.", status: "good" },
      { id: "c2-3", question: "What is the formula for the de Broglie wavelength?", answer: "λ = h / p, where h is Planck's constant and p is the momentum.", status: "again" },
    ],
  },
];

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: "event-1",
    title: "Computer Science Midterm",
    type: "exam",
    date: "2026-07-15",
    time: "09:00 - 11:30",
    description: "Data structures, runtime complexity analysis, and object-oriented paradigms.",
    subjectId: "sub-cs",
  },
  {
    id: "event-2",
    title: "Database Normalization PDF Submission",
    type: "assignment",
    date: "2026-07-14",
    time: "23:59 deadline",
    description: "Submit PDF report on Study OS portal upload box.",
    subjectId: "sub-cs",
  },
  {
    id: "event-3",
    title: "Advanced Math Study Group",
    type: "study",
    date: "2026-07-20",
    time: "14:00 - 16:30",
    description: "Reviewing Calculus Integration Techniques and Fourier transforms.",
    subjectId: "sub-math",
  },
  {
    id: "event-4",
    title: "Chemistry Lab Session",
    type: "other",
    date: "2026-07-12",
    time: "10:30 - 12:30",
    description: "Synthesis of acetylsalicylic acid (aspirin) and purification via recrystallization.",
    subjectId: "sub-chem",
  },
  {
    id: "event-5",
    title: "History of Art Quiz: The Renaissance",
    type: "exam",
    date: "2026-07-30",
    time: "13:00 - 14:00",
    description: "Focus on perspective, Leonardo's visual techniques, and Raphael.",
    subjectId: "sub-hist",
  },
];

export const INITIAL_RESOURCES: ResourceItem[] = [
  {
    id: "res-1",
    name: "Advanced Machine Learning Intro.pdf",
    type: "pdf",
    folder: "Lectures",
    url: "#",
    dateAdded: "2026-07-08",
    size: "4.2 MB",
    subjectId: "sub-cs",
  },
  {
    id: "res-2",
    name: "Quantum Mechanics Video Lecture.mp4",
    type: "video",
    folder: "Lectures",
    url: "#",
    dateAdded: "2026-07-05",
    size: "240.5 MB",
    subjectId: "sub-math",
  },
  {
    id: "res-3",
    name: "Organic Chem Lab Syllabus.pdf",
    type: "pdf",
    folder: "Lab Notes",
    url: "#",
    dateAdded: "2026-07-01",
    size: "1.8 MB",
    subjectId: "sub-chem",
  },
  {
    id: "res-4",
    name: "Medieval Architecture Slides.zip",
    type: "archive",
    folder: "Archive",
    url: "#",
    dateAdded: "2026-06-20",
    size: "82.3 MB",
    subjectId: "sub-hist",
  },
];

export const INITIAL_USER_STATS: UserStats = {
  name: "Alex Rivera",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=256&auto=format&fit=crop",
  level: 42,
  xp: 8420,
  xpNext: 12000,
  streak: 12,
  totalFocusTime: 1280,
  completedSessions: 32,
  effortIncrease: 14.2,
};

export const INITIAL_BADGES: Badge[] = [
  { id: "badge-1", name: "Night Owl", description: "Completed 5 study focus sessions between 12:00 AM and 4:00 AM.", icon: "Moon", unlocked: true, unlockedAt: "2026-07-02" },
  { id: "badge-2", name: "Deep Diver", description: "Logged a perfect 120-minute continuous Pomodoro study session.", icon: "ShieldAlert", unlocked: true, unlockedAt: "2026-07-05" },
  { id: "badge-3", name: "Quiz Master", description: "Scored 100% on three consecutive subject micro-quizzes.", icon: "Trophy", unlocked: true, unlockedAt: "2026-07-08" },
  { id: "badge-4", name: "Library Ghost", description: "Log in and complete at least one focus session for 10 days in a row.", icon: "Flame", unlocked: true, unlockedAt: "2026-07-10" },
  { id: "badge-5", name: "Renaissance Scholar", description: "Publish your first shared peer note on the global Resource Vault.", icon: "BookOpen", unlocked: false },
];

export const DEFAULT_SETTINGS: SystemSettings = {
  language: "English (US)",
  autoSave: true,
  soundEnabled: true,
  theme: "light",
  emailNotifications: true,
  pushNotifications: false,
  publicProfile: true,
  shareProgress: true,
};
